#include <stdio.h>

int main(){
    int n;
    scanf("%d",&n);
    if(n<1 || n>99) printf("-1");
    if(n==1) printf("nhat");
    if(n==2) printf("nhi");
    if(n==3) printf("tam");
    if(n==4) printf("tu");
    if(n==5) printf("ngu");
    if(n==6) printf("luc");
    if(n==7) printf("that");
    if(n==8) printf("bat");
    if(n==9) printf("cuu");
    if(n==10) printf("thap");
    if(n==11) printf("thap nhat");
    if(n==12) printf("thap nhi");
    if(n==13) printf("thap tam");
    if(n==14) printf("thap tu");
    if(n==15) printf("thap ngu");
    if(n==16) printf("thap luc");
    if(n==17) printf("thap that");
    if(n==18) printf("thap bat");
    if(n==19) printf("thap cuu");
    if(n==20) printf("nhi thap");
    if(n==21) printf("nhi thap nhat");
    if(n==22) printf("nhi thap nhi");
    if(n==23) printf("nhi thap tam");
    if(n==24) printf("nhi thap tu");
    if(n==25) printf("nhi thap ngu");
    if(n==26) printf("nhi thap luc");
    if(n==27) printf("nhi thap that");
    if(n==28) printf("nhi thap bat");
    if(n==29) printf("nhi thap cuu");
    if(n==30) printf("tam thap");
    if(n==31) printf("tam thap nhat");
    if(n==32) printf("tam thap nhi");
    if(n==33) printf("tam thap tam");
    if(n==34) printf("tam thap tu");
    if(n==35) printf("tam thap ngu");
    if(n==36) printf("tam thap luc");
    if(n==37) printf("tam thap that");
    if(n==38) printf("tam thap bat");
    if(n==39) printf("tam thap cuu");
    if(n==40) printf("tu thap");
    if(n==41) printf("tu thap nhat");
    if(n==42) printf("tu thap nhi");
    if(n==43) printf("tu thap tam");
    if(n==44) printf("tu thap tu");
    if(n==45) printf("tu thap ngu");
    if(n==46) printf("tu thap luc");
    if(n==47) printf("tu thap that");
    if(n==48) printf("tu thap bat");
    if(n==49) printf("tu thap cuu");
    if(n==50) printf("ngu thap");
    if(n==51) printf("ngu thap nhat");
    if(n==52) printf("ngu thap nhi");
    if(n==53) printf("nghu thap tam");
    if(n==54) printf("ngu thap tu");
    if(n==55) printf("ngu thap ngu");
    if(n==56) printf("ngu thap luc");
    if(n==57) printf("ngu thap that");
    if(n==58) printf("ngu thap bat ");
    if(n==59) printf("thap cuu");
    if(n==60) printf("luc thap");
    if(n==61) printf("luc thap nhat");
    if(n==62) printf("luc thap nhi");
    if(n==63) printf("luc thap tam");
    if(n==64) printf("luc thap tu");
    if(n==65) printf("luc thap ngu");
    if(n==66) printf("luc thap luc");
    if(n==67) printf("luc thap that");
    if(n==68) printf("luc thap bat");
    if(n==69) printf("luc thap cuu");
    if(n==70) printf("that thap");
    if(n==71) printf("that thap nhat");
    if(n==72) printf("that thap nhi");
    if(n==73) printf("that thap tam");
    if(n==74) printf("that thap tu");
    if(n==75) printf("that thap ngu");
    if(n==76) printf("that thap luc");
    if(n==77) printf("that thap that");
    if(n==78) printf("that thap bat");
    if(n==79) printf("that thap cuu");
    if(n==80) printf("luc thap nhi");
    if(n==81) printf("luc thap nhi");
    if(n==82) printf("luc thap nhi");
    if(n==83) printf("luc thap nhi");
    if(n==84) printf("luc thap nhi");
    if(n==85) printf("luc thap nhi");
    if(n==86) printf("luc thap nhi");
    if(n==87) printf("luc thap nhi");
    if(n==88) printf("luc thap nhi");


    return 0;
}